name: change_notifier
version: 0.24.0
description: Support for marking objects as observable
homepage: https://github.com/angulardart-community/change_notifier
environment:
  sdk: '>=2.12.0 <=3.0.0'

dependencies:
  collection: ^1.15.0
  dart_internal: ^0.2.2
  meta: ^1.7.0
  quiver: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^3.0.0
  lints: ^1.0.1
  test: ^1.17.12
